### ISSUE TITLE
Awesome Bolero?

### ISSUE THREAD

**Issue by IvanTheGeek** [fsbolero/website#14]
Can we include a set of links in the idea of "Awesome Lists" such as https://github.com/kunjee17/awesome-fable
for Bolero? I JUST found this page at https://spin.atomicobject.com/2019/06/20/javascript-free-web-dev-bolero/ that actaully is helping me understand everything alot, and I have been searching and trying things this whole week. Being able to find that from the borlero.io site would have been nice. 

I am asking if the "Awesome Borleo" should be directly part of this repo ( fsborleo/website ) or simply have a link in this repo to a new repo like  https://github.com/kunjee17/awesome-fable

**Comment by granicz** [comment]
There is no fixed rule on this, but awesome lists are usually collected/curated by the community, such as awesome-fable above, or Loic's [awesome-websharper](https://github.com/Tarmil/awesome-websharper). We would all be happy to contribute to such a list instead of owning it under fsbolero, unless of course an eventual list goes unattended, in which case it could be transferred, etc. So, anyone would like to start such a list?

**Comment by granicz** [comment]
As for whether a link would be on the Bolero website depends on the state of that list. Having a comprehensive collection of related items would be *literally* awesome, and definitely something to link to from the website.
