### ISSUE TITLE
Use yield instead of returning false/null for conditional attr

### ISSUE THREAD

**Issue by MichaelMay81** [fsbolero/website#49]
In the documentation I would suggest implicit yield instead of false/null.
Instead of the given example:
```
let myElement (isBlue: bool) =
    p [attr.style (if isBlue then "color: blue;" else null)] [
        text "Hello and welcome to my app!"
    ]
```
I would write:
```
let myElement (isBlue: bool) =
    p [if isBlue then attr.style "color: blue;"] [
        text "Hello and welcome to my app!"
    ]
```

**Comment by Tarmil** [comment]
That's exactly what this section warns against 😄 In usual F#, this would be fine, but due to Blazor's rendering algorithm, an attribute being present for one render and absent in the next can cause runtime errors. The only safe way to "remove" an attribute is to give it `null` or `false` as a value.

**Comment by MichaelMay81** [comment]
Argh, I am sorry. I totally overlooked that.
But it would be nice to have something like the Node.cond to hide that null or even better have something like Node.Cond and Node.Empty in Attr.

**Comment by Tarmil** [comment]
I think we can't really have equivalents of Node.Cond and Node.Empty unfortunately. Well, we could have Attr.Empty, in fact you can already do `Attr.Attrs []`, but it wouldn't help with this, because `Attrs` has a similar constraint where the number of items in the list mustn't change between renders. The best thing I can think of is something like this:

```fsharp
module attr =
    let maybe (f: obj -> Attr) (o: 'T option) =
        match o with
        | None -> null
        | Some x -> box x
        |> f

// Usage:
div [attr.maybe attr.style (if isBlue then Some "color: blue;" else None)] [
    text "Hello and welcome to my app!"
]
```

**Comment by MichaelMay81** [comment]
yeah. I saw that a function would only make sense for the case where the second condition returns null like:
``` fsharp
module attr =
   let ifOrNothing (cond: bool) (o: object) =
      match cond with
      | true -> o
      | false -> null
      
// Usage:
div [attr.style attr.ifOrNothing isBlue "color: blue;"] [
    text "Hello and welcome to my app!"
]
```
but that seems awfully specific...
